spring:
  application:
    name: blog

  mvc:
    cors:
      allowed-origins: "*"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/dh?useSSL=false&serverTimezone=UTC
    username: root
    password: Rkrenrl1!
    driver-class-name: com.mysql.cj.jdbc.Driver

